
package rs.ac.uns.ftn.xws.cbs.firma;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-03-09T05:07:09.722+01:00
 * Generated source version: 2.6.5
 * 
 */
 
public class FirmaPort_FirmaPort_Server{

    protected FirmaPort_FirmaPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new FirmaPortImpl();
        String address = "http://localhost:8080/firma";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new FirmaPort_FirmaPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
