
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package rs.ac.uns.ftn.xws.cbs.firma;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-03-27T23:19:21.041+01:00
 * Generated source version: 2.6.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "FirmaService",
                      portName = "Firma",
                      targetNamespace = "http://www.ftn.uns.ac.rs/xws/cbs/firma",
                      endpointInterface = "rs.ac.uns.ftn.xws.cbs.firma.Firma")
                      
public class FirmaImpl implements Firma {

    private static final Logger LOG = Logger.getLogger(FirmaImpl.class.getName());

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.firma.Firma#promet(rs.ac.uns.ftn.xws.cbs.faktura.Faktura  kupljeno )*
     */
    public rs.ac.uns.ftn.xws.cbs.faktura.Faktura promet(rs.ac.uns.ftn.xws.cbs.faktura.Faktura kupljeno) { 
        LOG.info("Executing operation promet");
        System.out.println(kupljeno);
        try {
            rs.ac.uns.ftn.xws.cbs.faktura.Faktura _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
