
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package rs.ac.uns.ftn.xws.cbs.firma;

import java.util.logging.Logger;

import singleton.MainFirmProcessor;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-04-12T03:49:26.924+02:00
 * Generated source version: 2.6.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "FirmaService",
                      portName = "Firma",
                      targetNamespace = "http://www.ftn.uns.ac.rs/xws/cbs/firma",
                      endpointInterface = "rs.ac.uns.ftn.xws.cbs.firma.Firma")
                      
public class FirmaImpl implements Firma {

    private static final Logger LOG = Logger.getLogger(FirmaImpl.class.getName());

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.firma.Firma#promet(rs.ac.uns.ftn.xws.cbs.faktura.Faktura  kupljeno )*
     */
    public rs.ac.uns.ftn.xws.cbs.faktura.Faktura promet(rs.ac.uns.ftn.xws.cbs.faktura.Faktura kupljeno) { 
        LOG.info("Executing operation promet");
        System.out.println(kupljeno);
        try {
        	
            return MainFirmProcessor.getInstance().process(kupljeno);
            
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
