package rs.ac.uns.ftn.xws.cbs.firma;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-03-27T23:19:21.068+01:00
 * Generated source version: 2.6.5
 * 
 */
@WebServiceClient(name = "FirmaService", 
                  targetNamespace = "http://www.ftn.uns.ac.rs/xws/cbs/firma") 
public class FirmaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.ftn.uns.ac.rs/xws/cbs/firma", "FirmaService");
    public final static QName Firma = new QName("http://www.ftn.uns.ac.rs/xws/cbs/firma", "Firma");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Nikola/Desktop/Fax/4 godina/2 semestar/xws/workspace/xws-cbs-firma/WEB-INF/xml/Firma.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FirmaService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Nikola/Desktop/Fax/4 godina/2 semestar/xws/workspace/xws-cbs-firma/WEB-INF/xml/Firma.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FirmaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FirmaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FirmaService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FirmaService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FirmaService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FirmaService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Firma
     */
    @WebEndpoint(name = "Firma")
    public Firma getFirma() {
        return super.getPort(Firma, Firma.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Firma
     */
    @WebEndpoint(name = "Firma")
    public Firma getFirma(WebServiceFeature... features) {
        return super.getPort(Firma, Firma.class, features);
    }

}
