package rs.ac.uns.ftn.xws.cbs.firma;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-23T17:22:08.127+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://www.ftn.uns.ac.rs/xws/cbs/firma", name = "XWSFirma")
@XmlSeeAlso({rs.ac.uns.ftn.xws.cbs.faktura.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface XWSFirma {

    @WebResult(name = "faktura", targetNamespace = "http://www.ftn.uns.ac.rs/xws/cbs/faktura", partName = "Faktura")
    @WebMethod
    public rs.ac.uns.ftn.xws.cbs.faktura.Faktura promet(
        @WebParam(partName = "Kupljeno", name = "faktura", targetNamespace = "http://www.ftn.uns.ac.rs/xws/cbs/faktura")
        rs.ac.uns.ftn.xws.cbs.faktura.Faktura kupljeno
    );
}
