
package rs.ac.uns.ftn.xws.cbs.firma;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-23T17:22:08.067+02:00
 * Generated source version: 2.6.5
 * 
 */
public final class XWSFirma_XWSFirmaPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.ftn.uns.ac.rs/xws/cbs/firma", "XWSFirmaService");

    private XWSFirma_XWSFirmaPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = XWSFirmaService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        XWSFirmaService ss = new XWSFirmaService(wsdlURL, SERVICE_NAME);
        XWSFirma port = ss.getXWSFirmaPort();  
        
        {
        System.out.println("Invoking promet...");
        rs.ac.uns.ftn.xws.cbs.faktura.Faktura _promet_kupljeno = new rs.ac.uns.ftn.xws.cbs.faktura.Faktura();
        rs.ac.uns.ftn.xws.cbs.faktura.Faktura _promet__return = port.promet(_promet_kupljeno);
        System.out.println("promet.result=" + _promet__return);


        }

        System.exit(0);
    }

}
