package rs.ac.uns.ftn.xws.cbs.firma;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-23T17:22:08.136+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebServiceClient(name = "XWSFirmaService", 
                  wsdlLocation = "classpath:xml/XWSFirma.wsdl",
                  targetNamespace = "http://www.ftn.uns.ac.rs/xws/cbs/firma") 
public class XWSFirmaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.ftn.uns.ac.rs/xws/cbs/firma", "XWSFirmaService");
    public final static QName XWSFirmaPort = new QName("http://www.ftn.uns.ac.rs/xws/cbs/firma", "XWSFirmaPort");
    static {
        URL url = XWSFirmaService.class.getResource("xws/XWSFirma.wsdl");
        
        if (url == null) {
            java.util.logging.Logger.getLogger(XWSFirmaService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "xml/XWSFirma.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public XWSFirmaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public XWSFirmaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XWSFirmaService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns XWSFirma
     */
    @WebEndpoint(name = "XWSFirmaPort")
    public XWSFirma getXWSFirmaPort() {
        return super.getPort(XWSFirmaPort, XWSFirma.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XWSFirma
     */
    @WebEndpoint(name = "XWSFirmaPort")
    public XWSFirma getXWSFirmaPort(WebServiceFeature... features) {
        return super.getPort(XWSFirmaPort, XWSFirma.class, features);
    }

}
