
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package rs.ac.uns.ftn.xws.cbs.firma;

import singleton.MainFirmProcessor;


/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-23T17:22:08.116+02:00
 * Generated source version: 2.6.5
 * 
 */

@javax.ejb.Stateless
@javax.jws.WebService(
                      serviceName = "XWSFirmaService",
                      portName = "XWSFirmaPort",
                      targetNamespace = "http://www.ftn.uns.ac.rs/xws/cbs/firma",
                      endpointInterface = "rs.ac.uns.ftn.xws.cbs.firma.XWSFirma")
                      
public class XWSFirmaImpl implements XWSFirma {

    
    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.firma.XWSFirma#promet(rs.ac.uns.ftn.xws.cbs.faktura.Faktura  kupljeno )*
     */
    public rs.ac.uns.ftn.xws.cbs.faktura.Faktura promet(rs.ac.uns.ftn.xws.cbs.faktura.Faktura kupljeno) { 
        //LOG.info("Executing operation promet");
        System.out.println(kupljeno);
        try {
            return MainFirmProcessor.getInstance().process(kupljeno);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
