package webservices;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-23T17:53:36.390+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebServiceClient(name = "XWSBankaService", 
                  wsdlLocation = "/home/nikola/workspace/xws/xws-cbs-banka/WEB-INF/xml/XWSBanka.wsdl",
                  targetNamespace = "http://www.ftn.uns.ac.rs/xws/cbs/banka") 
public class XWSBankaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.ftn.uns.ac.rs/xws/cbs/banka", "XWSBankaService");
    public final static QName XWSBankaPort = new QName("http://www.ftn.uns.ac.rs/xws/cbs/banka", "XWSBankaPort");
    static {
        URL url = XWSBankaService.class.getResource("/home/nikola/workspace/xws/xws-cbs-banka/WEB-INF/xml/XWSBanka.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(XWSBankaService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/home/nikola/workspace/xws/xws-cbs-banka/WEB-INF/xml/XWSBanka.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public XWSBankaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public XWSBankaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XWSBankaService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns XWSBanka
     */
    @WebEndpoint(name = "XWSBankaPort")
    public XWSBanka getXWSBankaPort() {
        return super.getPort(XWSBankaPort, XWSBanka.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XWSBanka
     */
    @WebEndpoint(name = "XWSBankaPort")
    public XWSBanka getXWSBankaPort(WebServiceFeature... features) {
        return super.getPort(XWSBankaPort, XWSBanka.class, features);
    }

}
